version: "3.9"
services:
  postgres:
    build: ./database
    container_name: c_database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=fhbybr
      - POSTGRES_DB=hospital
      - PGHOST=postgres
      - PGPORT=5432
  server:
    build: ./server
    container_name: c_server
    ports:
      - 5000:5000
    depends_on:
      - postgres
  client:
    build: ./client
    container_name: c_client
    ports:
      - 3000:3000
    stdin_open: true
    tty: true