const Router = require('express')
const router = new Router()
const doctorController = require('../controllers/doctorController')
const dauthMiddleware = require('../middleware/dauthMiddleware')
const checkRole = require('../middleware/checkRoleMiddleware')
router.post('/create', checkRole('HEAD_PHYSICIAN'), doctorController.create)
router.post('/login',doctorController.login)
router.get('/auth',dauthMiddleware, doctorController.check)
router.get('/',doctorController.getAll)
router.get('/:id',doctorController.getOne)
router.post('/patients', doctorController.getPatients)
module.exports = router
