const Router = require('express')
const router = new Router()
const doctorController = require('../controllers/doctorController')
//const authMiddleware = require('../middleware/authMiddleware')
router.post('/create',doctorController.create)
router.post('/login',doctorController.login)
router.get('/auth',doctorController.check)
router.get('/',doctorController.getAll)
router.get('/:id',doctorController.getOne)
module.exports = router
